{
  "Identifier": "CVE-2022-41910",
  "PackageSlug": "pypi/tensorflow",
  "Title": "Out-of-bounds Read",
  "Description": "TensorFlow is an open source platform for machine learning. The function MakeGrapplerFunctionItem takes arguments that determine the sizes of inputs and outputs. If the inputs given are greater than or equal to the sizes of the outputs, an out-of-bounds memory read or a crash is triggered. We have patched the issue in GitHub commit a65411a1d69edfb16b25907ffb8f73556ce36bb7. The fix will be included in TensorFlow 2.11.0. We will also cherrypick this commit on TensorFlow 2.8.4, 2.9.3, and 2.10.1.",
  "Date": "2022-12-08",
  "Pubdate": "2022-12-06",
  "AffectedRange": "\u003c2.8.4||\u003e=2.9.0,\u003c2.9.3||==2.10.0",
  "FixedVersions": [
    "2.8.4",
    "2.9.3",
    "2.10.1"
  ],
  "AffectedVersions": "All versions before 2.8.4, all versions starting from 2.9.0 before 2.9.3, version 2.10.0",
  "NotImpacted": "All versions starting from 2.8.4 before 2.9.0, all versions starting from 2.9.3 before 2.10.0, all versions after 2.10.0",
  "Solution": "Upgrade to versions 2.8.4, 2.9.3, 2.10.1 or above.",
  "Urls": [
    "https://nvd.nist.gov/vuln/detail/CVE-2022-41910",
    "https://github.com/tensorflow/tensorflow/commit/a65411a1d69edfb16b25907ffb8f73556ce36bb7",
    "https://github.com/tensorflow/tensorflow/security/advisories/GHSA-frqp-wp83-qggv",
    "https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/utils/functions.cc#L221",
    "https://github.com/advisories/GHSA-frqp-wp83-qggv"
  ],
  "CvssV2": "",
  "CvssV3": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
  "UUID": "36409fb6-c5cd-45e7-86f8-8e13718905f8"
}