{
  "Severity": "HIGH",
  "UpdatedAt": "2022-01-06T18:29:32Z",
  "Package": {
    "Ecosystem": "RUST",
    "Name": "libpulse-binding"
  },
  "Advisory": {
    "DatabaseId": 8105,
    "Id": "GSA_kwCzR0hTQS1qcXB2LWptNG0tODZqOc0fqQ",
    "GhsaId": "GHSA-jqpv-jm4m-86j9",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2018-25028"
      },
      {
        "Url": "https://raw.githubusercontent.com/rustsec/advisory-db/main/crates/libpulse-binding/RUSTSEC-2018-0021.md"
      },
      {
        "Url": "https://rustsec.org/advisories/RUSTSEC-2018-0021.html"
      },
      {
        "Url": "https://github.com/advisories/GHSA-jqpv-jm4m-86j9"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-jqpv-jm4m-86j9"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2018-25028"
      }
    ],
    "Description": "An issue was discovered in the libpulse-binding crate before 1.2.1 for Rust. get_context can cause a use-after-free.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2022-01-06T22:17:50Z",
    "Severity": "HIGH",
    "Summary": "Use After Free in libpulse-binding",
    "UpdatedAt": "2023-02-03T05:03:45Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 7.5,
      "VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "1.2.1"
      },
      "VulnerableVersionRange": "\u003c 1.2.1"
    }
  ]
}