{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": [
      {
        "children": [
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:a:ibm:app_connect_enterprise:*:*:*:*:*:*:*:*",
                "cpe_name": [],
                "versionEndIncluding": "11.0.0.19",
                "versionStartIncluding": "11.0.0.17",
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:ibm:app_connect_enterprise:12.0.4.0:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              },
              {
                "cpe23Uri": "cpe:2.3:a:ibm:app_connect_enterprise:12.0.5.0:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": true
              }
            ],
            "operator": "OR"
          },
          {
            "children": [],
            "cpe_match": [
              {
                "cpe23Uri": "cpe:2.3:o:ibm:aix:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": false
              },
              {
                "cpe23Uri": "cpe:2.3:o:linux:linux_kernel:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": false
              },
              {
                "cpe23Uri": "cpe:2.3:o:microsoft:windows:-:*:*:*:*:*:*:*",
                "cpe_name": [],
                "vulnerable": false
              }
            ],
            "operator": "OR"
          }
        ],
        "cpe_match": [],
        "operator": "AND"
      }
    ]
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "psirt@us.ibm.com",
      "ID": "CVE-2022-42439"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "IBM App Connect Enterprise 11.0.0.17 through 11.0.0.19 and 12.0.4.0 and 12.0.5.0 contains an unspecified vulnerability in the Discovery Connector nodes which may cause a 3rd party systemâ€™s credentials to be exposed to a privileged attacker. IBM X-Force ID: 238211."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-200"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://exchange.xforce.ibmcloud.com/vulnerabilities/238211",
          "refsource": "MISC",
          "tags": [
            "VDB Entry",
            "Vendor Advisory"
          ],
          "url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/238211"
        },
        {
          "name": "https://www.ibm.com/support/pages/node/6952435",
          "refsource": "MISC",
          "tags": [],
          "url": "https://www.ibm.com/support/pages/node/6952435"
        }
      ]
    }
  },
  "impact": {
    "baseMetricV3": {
      "cvssV3": {
        "attackComplexity": "LOW",
        "attackVector": "NETWORK",
        "availabilityImpact": "NONE",
        "baseScore": 4.9,
        "baseSeverity": "MEDIUM",
        "confidentialityImpact": "HIGH",
        "integrityImpact": "NONE",
        "privilegesRequired": "HIGH",
        "scope": "UNCHANGED",
        "userInteraction": "NONE",
        "vectorString": "CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:H/I:N/A:N",
        "version": "3.1"
      },
      "exploitabilityScore": 1.2,
      "impactScore": 3.6
    }
  },
  "lastModifiedDate": "2023-02-17T17:15Z",
  "publishedDate": "2023-02-06T21:15Z"
}