{
  "Title": "Security update for python-Django",
  "Tracking": {
    "ID": "openSUSE-SU-2023:0309-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2023-10-20T22:01:23Z",
    "CurrentReleaseDate": "2023-10-20T22:01:23Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2023-10-20T22:01:23Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python-Django",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python-Django fixes the following issues:\n\n- CVE-2023-43665: Denial-of-service in django.utils.text.Truncator (boo#1215978).\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "openSUSE-2023-309",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": null
  },
  "References": [
    {
      "URL": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/ATEWH7NL3QAM2APATNLZKNXCJ4YC2VIW/",
      "Description": "E-Mail link for openSUSE-SU-2023:0309-1"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1215978",
      "Description": "SUSE Bug 1215978"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2023-43665/",
      "Description": "SUSE CVE CVE-2023-43665 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2023-43665",
      "Description": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "moderate"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2023-43665.html",
          "Description": "CVE-2023-43665"
        },
        {
          "URL": "https://bugzilla.suse.com/1215978",
          "Description": "SUSE Bug 1215978"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": null
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}