{
  "Title": "Security update for python-Django",
  "Tracking": {
    "ID": "SUSE-SU-2024:3161-1",
    "Status": "Final",
    "Version": "1",
    "InitialReleaseDate": "2024-09-06T10:16:42Z",
    "CurrentReleaseDate": "2024-09-06T10:16:42Z",
    "RevisionHistory": [
      {
        "Number": "1",
        "Date": "2024-09-06T10:16:42Z",
        "Description": "current"
      }
    ]
  },
  "Notes": [
    {
      "Text": "Security update for python-Django",
      "Title": "Topic",
      "Type": "Summary"
    },
    {
      "Text": "This update for python-Django fixes the following issues:\n\n- CVE-2024-45230: Fixed potential denial-of-service vulnerability in django.utils.html.urlize(). (bsc#1229823)\n- CVE-2024-45231: Fixed potential user email enumeration via response status on password reset. (bsc#1229824)\n",
      "Title": "Details",
      "Type": "General"
    },
    {
      "Text": "The CVRF data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
      "Title": "Terms of Use",
      "Type": "Legal Disclaimer"
    },
    {
      "Text": "SUSE-2024-3161,SUSE-SLE-Module-Packagehub-Subpackages-15-SP6-2024-3161,openSUSE-SLE-15.6-2024-3161",
      "Title": "Patchnames",
      "Type": "Details"
    }
  ],
  "ProductTree": {
    "Relationships": [
      {
        "ProductReference": "python311-Django-4.2.11-150600.3.9.1",
        "RelatesToProductReference": "SUSE Linux Enterprise Module for Package Hub 15 SP6",
        "RelationType": "Default Component Of"
      },
      {
        "ProductReference": "python311-Django-4.2.11-150600.3.9.1",
        "RelatesToProductReference": "openSUSE Leap 15.6",
        "RelationType": "Default Component Of"
      }
    ]
  },
  "References": [
    {
      "URL": "https://www.suse.com/support/update/announcement/2024/suse-su-20243161-1/",
      "Description": "Link for SUSE-SU-2024:3161-1"
    },
    {
      "URL": "https://lists.suse.com/pipermail/sle-updates/2024-September/036802.html",
      "Description": "E-Mail link for SUSE-SU-2024:3161-1"
    },
    {
      "URL": "https://www.suse.com/support/security/rating/",
      "Description": "SUSE Security Ratings"
    },
    {
      "URL": "https://bugzilla.suse.com/1229823",
      "Description": "SUSE Bug 1229823"
    },
    {
      "URL": "https://bugzilla.suse.com/1229824",
      "Description": "SUSE Bug 1229824"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-45230/",
      "Description": "SUSE CVE CVE-2024-45230 page"
    },
    {
      "URL": "https://www.suse.com/security/cve/CVE-2024-45231/",
      "Description": "SUSE CVE CVE-2024-45231 page"
    }
  ],
  "Vulnerabilities": [
    {
      "CVE": "CVE-2024-45230",
      "Description": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-45230.html",
          "Description": "CVE-2024-45230"
        },
        {
          "URL": "https://bugzilla.suse.com/1229823",
          "Description": "SUSE Bug 1229823"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.9.1",
            "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.9.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    },
    {
      "CVE": "CVE-2024-45231",
      "Description": "** RESERVED ** This candidate has been reserved by an organization or individual that will use it when announcing a new security problem. When the candidate has been publicized, the details for this candidate will be provided.",
      "Threats": [
        {
          "Type": "Impact",
          "Severity": "important"
        }
      ],
      "References": [
        {
          "URL": "https://www.suse.com/security/cve/CVE-2024-45231.html",
          "Description": "CVE-2024-45231"
        },
        {
          "URL": "https://bugzilla.suse.com/1229824",
          "Description": "SUSE Bug 1229824"
        }
      ],
      "ProductStatuses": [
        {
          "Type": "Fixed",
          "ProductID": [
            "SUSE Linux Enterprise Module for Package Hub 15 SP6:python311-Django-4.2.11-150600.3.9.1",
            "openSUSE Leap 15.6:python311-Django-4.2.11-150600.3.9.1"
          ]
        }
      ],
      "CVSSScoreSets": {}
    }
  ]
}