{
  "Severity": "CRITICAL",
  "UpdatedAt": "2022-03-21T22:37:12Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "ecdsa"
  },
  "Advisory": {
    "DatabaseId": 2017,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLThxeGotZjlyaC05Zmcy",
    "GhsaId": "GHSA-8qxj-f9rh-9fg2",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2019-14859"
      },
      {
        "Url": "https://github.com/warner/python-ecdsa/issues/114"
      },
      {
        "Url": "https://github.com/warner/python-ecdsa/pull/115"
      },
      {
        "Url": "https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2019-14859"
      },
      {
        "Url": "https://github.com/warner/python-ecdsa/releases/tag/python-ecdsa-0.13.3"
      },
      {
        "Url": "https://pypi.org/project/ecdsa/0.13.3/"
      },
      {
        "Url": "https://github.com/advisories/GHSA-8qxj-f9rh-9fg2"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-8qxj-f9rh-9fg2"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2019-14859"
      }
    ],
    "Description": "A flaw was found in all python-ecdsa versions before 0.13.3, where it did not correctly verify whether signatures used DER encoding. Without this verification, a malformed signature could be accepted, making the signature malleable. Without proper verification, an attacker could use a malleable signature to create false transactions.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2020-04-01T16:35:26Z",
    "Severity": "CRITICAL",
    "Summary": "Improper Verification of Cryptographic Signature in Pure-Python ECDSA",
    "UpdatedAt": "2023-02-01T05:03:04Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 9.1,
      "VectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:N"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "0.13.3"
      },
      "VulnerableVersionRange": "\u003c 0.13.3"
    }
  ]
}