{
  "id": "CVE-2021-40839",
  "state": [
    {
      "fixed": false,
      "published": true,
      "repo": "3.13-community",
      "packageName": "py3-rencode",
      "packageVersion": "1.0.6-r4"
    },
    {
      "fixed": false,
      "published": true,
      "repo": "3.14-community",
      "packageName": "py3-rencode",
      "packageVersion": "1.0.6-r5"
    },
    {
      "fixed": false,
      "published": true,
      "repo": "3.15-community",
      "packageName": "py3-rencode",
      "packageVersion": "1.0.6-r5"
    },
    {
      "fixed": false,
      "published": true,
      "repo": "3.16-community",
      "packageName": "py3-rencode",
      "packageVersion": "1.0.6-r6"
    },
    {
      "fixed": false,
      "published": true,
      "repo": "edge-community",
      "packageName": "py3-rencode",
      "packageVersion": "1.0.6-r5"
    }
  ],
  "cpeMatch": [
    {
      "minimumVersion": "",
      "minimumVersionOp": "\u003e=",
      "maximumVersion": "1.0.6",
      "maximumVersionOp": "\u003c="
    }
  ]
}