{
  "Severity": "HIGH",
  "UpdatedAt": "2023-01-04T19:33:11Z",
  "Package": {
    "Ecosystem": "PIP",
    "Name": "GitPython"
  },
  "Advisory": {
    "DatabaseId": 197282,
    "Id": "GSA_kwCzR0hTQS1oY3BqLXFwNTUtZ2ZwaM4AAwKi",
    "GhsaId": "GHSA-hcpj-qp55-gfph",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2022-24439"
      },
      {
        "Url": "https://security.snyk.io/vuln/SNYK-PYTHON-GITPYTHON-3113858"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/blob/bec61576ae75803bc4e60d8de7a629c194313d1c/git/repo/base.py#L1249"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/issues/1515"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/blob/bec61576ae75803bc4e60d8de7a629c194313d1c/git/repo/base.py%23L1249"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/releases/tag/3.1.30"
      },
      {
        "Url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/IKMVYKLWX62UEYKAN64RUZMOIAMZM5JN/"
      },
      {
        "Url": "https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/SJHN3QUXPJIMM6SULIR3PR34UFWRAE7X/"
      },
      {
        "Url": "https://github.com/gitpython-developers/GitPython/commit/2625ed9fc074091c531c27ffcba7902771130261"
      },
      {
        "Url": "https://github.com/advisories/GHSA-hcpj-qp55-gfph"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-hcpj-qp55-gfph"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2022-24439"
      }
    ],
    "Description": "All versions of package gitpython are vulnerable to Remote Code Execution (RCE) due to improper user input validation, which makes it possible to inject a maliciously crafted remote URL into the clone command. Exploiting this vulnerability is possible because the library makes external calls to git without sufficient sanitization of input arguments.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2022-12-06T06:30:17Z",
    "Severity": "HIGH",
    "Summary": "GitPython vulnerable to Remote Code Execution due to improper user input validation",
    "UpdatedAt": "2023-04-06T20:42:56Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 8.1,
      "VectorString": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:H"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "3.1.30"
      },
      "VulnerableVersionRange": "\u003c= 3.1.29"
    }
  ]
}