{
  "Severity": "HIGH",
  "UpdatedAt": "2021-08-19T21:24:20Z",
  "Package": {
    "Ecosystem": "RUST",
    "Name": "untrusted"
  },
  "Advisory": {
    "DatabaseId": 5295,
    "Id": "MDE2OlNlY3VyaXR5QWR2aXNvcnlHSFNBLXdxOGYtNDZ3dy02YzJo",
    "GhsaId": "GHSA-wq8f-46ww-6c2h",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2018-20989"
      },
      {
        "Url": "https://github.com/briansmith/untrusted/pull/20"
      },
      {
        "Url": "https://rustsec.org/advisories/RUSTSEC-2018-0001.html"
      },
      {
        "Url": "https://github.com/advisories/GHSA-wq8f-46ww-6c2h"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-wq8f-46ww-6c2h"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2018-20989"
      }
    ],
    "Description": "An issue was discovered in the untrusted crate before 0.6.2 for Rust. Error handling can trigger an integer underflow and panic.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2021-08-25T20:43:49Z",
    "Severity": "HIGH",
    "Summary": "Integer underflow in untrusted",
    "UpdatedAt": "2023-01-11T05:05:46Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 7.5,
      "VectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": "0.6.2"
      },
      "VulnerableVersionRange": "\u003c 0.6.2"
    }
  ]
}