{
  "configurations": {
    "CVE_data_version": "4.0",
    "nodes": []
  },
  "cve": {
    "CVE_data_meta": {
      "ASSIGNER": "security@huntr.dev",
      "ID": "CVE-2023-3574"
    },
    "data_format": "MITRE",
    "data_type": "CVE",
    "data_version": "4.0",
    "description": {
      "description_data": [
        {
          "lang": "en",
          "value": "Improper Authorization in GitHub repository pimcore/customer-data-framework prior to 3.4.1."
        }
      ]
    },
    "problemtype": {
      "problemtype_data": [
        {
          "description": [
            {
              "lang": "en",
              "value": "CWE-285"
            }
          ]
        }
      ]
    },
    "references": {
      "reference_data": [
        {
          "name": "https://huntr.dev/bounties/1dcb4f01-e668-4aa3-a6a3-838532e500c6",
          "refsource": "MISC",
          "tags": [],
          "url": "https://huntr.dev/bounties/1dcb4f01-e668-4aa3-a6a3-838532e500c6"
        },
        {
          "name": "https://github.com/pimcore/customer-data-framework/commit/f15668c86db254e86ba7ac895bc3cdd1a2a3cc45",
          "refsource": "MISC",
          "tags": [],
          "url": "https://github.com/pimcore/customer-data-framework/commit/f15668c86db254e86ba7ac895bc3cdd1a2a3cc45"
        }
      ]
    }
  },
  "impact": {},
  "lastModifiedDate": "2023-07-10T16:27Z",
  "publishedDate": "2023-07-10T16:15Z"
}