{
  "Severity": "MODERATE",
  "UpdatedAt": "2021-11-19T13:19:44Z",
  "Package": {
    "Ecosystem": "GO",
    "Name": "github.com/ethereum/go-ethereum"
  },
  "Advisory": {
    "DatabaseId": 6024,
    "Id": "GSA_kwCzR0hTQS01bThmLWNocnYtN3J3Nc0XiA",
    "GhsaId": "GHSA-5m8f-chrv-7rw5",
    "References": [
      {
        "Url": "https://nvd.nist.gov/vuln/detail/CVE-2021-43668"
      },
      {
        "Url": "https://github.com/ethereum/go-ethereum/issues/23866"
      },
      {
        "Url": "https://github.com/syndtr/goleveldb/issues/373"
      },
      {
        "Url": "https://github.com/advisories/GHSA-5m8f-chrv-7rw5"
      }
    ],
    "Identifiers": [
      {
        "Type": "GHSA",
        "Value": "GHSA-5m8f-chrv-7rw5"
      },
      {
        "Type": "CVE",
        "Value": "CVE-2021-43668"
      }
    ],
    "Description": "Go-Ethereum 1.10.9 nodes crash (denial of service) after receiving a serial of messages and cannot be recovered. They will crash with \"runtime error: invalid memory address or nil pointer dereference\" and arise a SEGV signal.",
    "Origin": "UNSPECIFIED",
    "PublishedAt": "2021-11-23T18:04:47Z",
    "Severity": "MODERATE",
    "Summary": "Denial of Service in Go-Ethereum",
    "UpdatedAt": "2023-02-01T05:06:18Z",
    "WithdrawnAt": "",
    "CVSS": {
      "Score": 0,
      "VectorString": ""
    }
  },
  "Versions": [
    {
      "FirstPatchedVersion": {
        "Identifier": ""
      },
      "VulnerableVersionRange": "\u003c= 1.10.9"
    }
  ]
}